### PR TITLE
some minor edits for section 01

### PR DESCRIPTION
**Pull request by ALShum**
some minor edits, comments indicated in brackets [[[ ]]]

### CODE REVIEW

**Comment by ALShum** [comment]
closing this PR, combined with section 02 edits in #2

**Comment by happyrabbit** [comment]
[[[I would argue that as a data scientist, it should be possible to start with something general and unspecific like question 1 and eventually get to question 2.  In this way question 1 is the underlying question and question 2 is one method of helping to answer question 1]]]

Good point. I agree. Based on that, I added these words:

"As a data scientist, you may start with something general and unspecific like question 1 and eventually get to question 2.  Effective communication and in-depth domain knowledge about the business problem are essential to convert a general business question into a solvable analytical problem. Domain knowledge helps data scientist communicate with the language the other people can understand and obtain the required information. "

**Comment by happyrabbit** [comment]
[[[to be clear on neural nets, the linear combinations of predictors are put through non-linear activation functions, deeper neural nets have many layers of non-linear transformation]]]

I like the clarification. I added it in as a footnote. Also, there is a new chapter on Neural Network: http://scientistcafe.com/CE_JSM2017/neural-network.html Can you take a look at it too? Not sure if I explain neural nets correctly and clearly. 

I am still working on the summary of algorithms.

**Comment by happyrabbit** [comment]
"In the above code, x is the R object wrapping the SparkDataFrame; the response is y-variable, features is the collection of explanatory variables. "

[[[not quite following this part]]]

Ming wrote "Big Data Cloud Platform" and "Soft Skills for Data Scientists." So I need to talk to him about the clarification. I don't have too much experience with sparklyr. SparkDataFrame is not an R data frame. But through sparklyr package, you can manipulate it as if a data frame. 

Also, the sections are too short in this chapter. We may need to combine some.

**Pull request closed without merging**
